application: vn-production
version: add-ships
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /login
  script: handlers.app
  secure: always
  login: required

- url: .*
  script: handlers.app
  secure: always

